# Generated by Django 4.1.1 on 2022-10-03 10:41

import crud.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UdsMeta',
            fields=[
                ('oid', models.BigIntegerField(blank=True, default=crud.models.auto_incr_oid, null=True)),
                ('uniq_id', crud.models.UnlimitedCharField(primary_key=True, serialize=False)),
                ('stor_folder', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('stor_phys', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('stor_reason', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('stor_date', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('stor_dept', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('stor_person', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('stor_desc', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('stor_fmts', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('stor_units', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_name', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('type_of_work', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_synopsis', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_type', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_sub_type', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_assoc_inv_nums', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_date', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_year', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_authors', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_orgs', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_restrict', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_rights', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_rdoc_name', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_rdoc_num', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_terms', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_sources', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_supl_info', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_main_min', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_supl_min', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_group_min', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_assoc_geol', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('spat_atd_ate', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('spat_loc', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('spat_num_grid', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('spat_coords_source', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('spat_toponim', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('inf_type', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('inf_media', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('path_others', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_main_group', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_sub_group', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('path_local', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('path_cloud', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('status', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('timecode', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('obj_sub_group_ref', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('path_local_ref', crud.models.UnlimitedCharField(blank=True, null=True)),
                ('path_cloud_ref', crud.models.UnlimitedCharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uds_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('typeAction', models.CharField(max_length=100)),
                ('order', models.BooleanField()),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
                ('udsMeta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', related_query_name='statistic', to='crud.udsmeta')),
            ],
            options={
                'db_table': 'statistic',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeAppend', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('my_user', models.ManyToManyField(related_name='orders', related_query_name='order', to=settings.AUTH_USER_MODEL)),
                ('udsMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.udsmeta')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Bascet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('udsMeta', models.ManyToManyField(related_name='bascets', related_query_name='bascet', to='crud.udsmeta')),
            ],
            options={
                'db_table': 'bascet',
            },
        ),
    ]
