# Generated by Django 4.1.1 on 2022-10-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0002_test_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('typeAction', models.CharField(max_length=100)),
                ('order', models.BooleanField()),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL)),
                ('udsMeta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', related_query_name='history', to='crud.udsmeta')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
