# Generated by Django 4.1.1 on 2022-10-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_history_remove_statistic_my_user_and_more'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='udsmeta',
            options={},
        ),

    ]
