# Generated by Django 4.1.1 on 2022-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_statistic_my_user_remove_statistic_udsmeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test',
            },
        ),

    ]
