# Generated by Django 4.1.1 on 2022-10-21 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crud', '0005_test_remove_statistic_my_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('departament', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        
    ]
