# Generated by Django 4.1.2 on 2022-11-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='udsmetagrrstage',
            options={'managed': False},
        ),
    ]
