# Generated by Django 4.1.2 on 2022-12-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grr', '0002_alter_udsmetagrrstage_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='udsmetagrrstage',
            table='uds_meta_grr_stage',
        ),
    ]
